
SET(BUILD_EXAMPLES OFF CACHE BOOL "")
SET(BUILD_TESTING OFF CACHE BOOL "")

SET(CMAKE_BUILD_TYPE "RELEASE" CACHE STRING "")

SET(WRAP_DEFAULT OFF CACHE BOOL "")
SET(WRAP_PYTHON ON CACHE BOOL "")
SET(SimpleITK_PYTHON_WHEEL ON CACHE BOOL "")
SET(SimpleITK_BUILD_DISTRIBUTE ON CACHE BOOL "")

