
SET(BUILD_EXAMPLES OFF CACHE BOOL "")
SET(BUILD_TESTING OFF CACHE BOOL "")

SET(CMAKE_BUILD_TYPE "RELEASE" CACHE STRING "")

SET(CMAKE_CXX_FLAGS "/MP" CACHE STRING "")
SET(CMAKE_C_FLAGS "/MP" CACHE STRING "")

SET(WRAP_DEFAULT OFF CACHE BOOL "")
SET(WRAP_PYTHON ON CACHE BOOL "")

