require 'inifile'
require 'date'

# Adapted from https://gist.github.com/mkubenka/33b542cbd82614fe7f8b
#

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.guest = "windows"
  config.vm.boot_timeout = 600

  config.vm.provider :aws do |aws, override|
    # https://gist.github.com/amosshapira/e043ef116bfdfe92e3cd
    aws_credentials = IniFile.load(File.expand_path('~/.aws/credentials'))
    aws.access_key_id = aws_credentials['default']['aws_access_key_id']
    aws.secret_access_key = aws_credentials['default']['aws_secret_access_key']

    aws.region = 'us-east-1'

    aws.keypair_name = "chen-keypair" # << FIXME
    #aws.ami = "ami-c343ecb0" # Microsoft Windows Server 2012 Base
    aws.ami = "ami-0d41aee8a57fdb850" # MS Windows Server 2016 Base

    aws.instance_type = "t2.xlarge"
    aws.terminate_on_shutdown = true
    aws.security_groups = ["sg-9ee579fa"] # << FIXME
    aws.subnet_id = "subnet-47eb9922" # << FIXME
    aws.associate_public_ip = true

    # aws.spot_instance = true
    # aws.spot_max_price = 0.0155
    # aws.spot_valid_until = DateTime.now + (3.0/24)
    aws.tags = {
      'Name' => 'vagrant-test'
    }

    aws.user_data = File.read("user_data.txt")

    override.vm.communicator = "winrm"
    override.winrm.username = "Administrator"
    override.winrm.password = "VagrantRocks"

    override.vm.synced_folder ".", "/vagrant", disabled: true
  end
end
